---

- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        This is CTPIS private network.
        Please leave immediately if you are not authorized personal.
      state: present

  - name: Add loopback

    ios_interface:
      name: Loopback21
      state: present 
